server:
  port: 9094
spring:
  thymeleaf:
    prefix: classpath:/templates/
fiserv:
  baseUrl: https://cert.api.firstdata.com/gateway/v2
  apiKey: 3Ha4sMqYSYKd85PjfXN0HZJvZMAIU2O8
  apiSecret: ONxJtdKgFmBjZfb4sttplvrXWMCdgLVLFXCMpD8hF0y
  storeId: 6201172
  challengeWithoutIframe: 4147463011110059
  challengeWithIframe: 5204740000002745
  frictionlessWithoutIframe: 4147463011110083
  frictionlessWithIframe: 4265880000000007
  termURL: https://698495hz29.zicp.fun/webhook


