server:
  port: 9094
spring:
  thymeleaf:
    prefix: classpath:/templates/
fiserv:
  baseUrl: https://prod.api.firstdata.com/gateway/v2
  apiKey: 44Ou627XdacEhR0prGcwSqVfs1UAGWoj
  apiSecret: fG0eEaJpCQHlZyiAiTQ6X0MCWAGjyNX8L1vmN95YG83
  storeId: 6204778
  termURL: https://698495hz29.zicp.fun/webhook
  cardInfoList:
    - cardNumber: 4041170044403255
      expirationMonth: "09"
      expirationYear: 23
      cvc: 23


